--- #YAML:1.0
name: IP-Route-Reject
version: 0.2
author:
  - ~
abstract: Perl module for adding/removing reject routes
license: artistic
requires:
  IPC::Cmd: 0.04
provides:
  IP::Route::Reject:
    file: lib/IP/Route/Reject.pm
    version: 0.2
generated_by: Module::Build version 0.24
